app = "pack-calculator"
primary_region = "ord"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8080"
  PACK_SIZES = "250,500,1000,2000,5000"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0

  [[http_service.checks]]
    interval = "30s"
    timeout = "5s"
    path = "/"

[[vm]]
  size = "shared-cpu-1x"
  memory = "256mb"
